name: Distribute template updates
on:
  push:
    paths:
      - '.github/workflows/*'
      - '.github/defaults/*'
      - '.github/pull_request_template.md'

jobs:
  Get-repo-list:
    # Get repos that need to be updated 
    runs-on: ubuntu-latest
    # if: ${{ (github.repository == 'bo-sfl/personal-template') && ((github.ref == 'refs/heads/main') || (github.ref == 'refs/heads/main')) }}
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - run: echo ${{ github.ref }}
    - run: echo ${{ github.repository }}
    - name: test
      if : ${{ github.repository == 'bo-sfl/personal-template' }}
      run: echo "COOL"
    - name: test
      if: ${{ (github.ref == 'refs/heads/main') || (github.ref == 'refs/heads/master') }}
      run: echo "COOL"
    - name: test
      if : $${{ (github.repository == 'bo-sfl/personal-template') && ((github.ref == 'refs/heads/main') || (github.ref == 'refs/heads/main')) }}
      run: echo "COOL"
    - name: Find all workable repos
      id: repo_list
      uses: SFLScientific/fetch-repo-list@main
      with:
        last_active: 3
        token: ${{ secrets.ORG_DISTRIBUTE_TOKEN }}
        ignore_repos: "['bo-sfl/personal-template']" 

    - name: Pass repo list to output
      id: set-matrix
      run: |
        JSON="${{ steps.repo_list.outputs.repo_list }}"
        echo "::set-output name=matrix::${JSON//'%'/'%25'}"


  Distribute-updates:
    needs: Get-repo-list
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.Get-repo-list.outputs.matrix)}}
    steps:
    - name: Fetch the template master
      uses: actions/checkout@master
      with:
        path: template
        lfs: False

    - name: Fetch the project repo master
      uses: actions/checkout@master
      with:
        path: project
        lfs: False
        repository: ${{ matrix.repo }}
        token: ${{ secrets.ORG_DISTRIBUTE_TOKEN }}

    - name: Populate changes
      run: |
        cp -r template/.github/workflows project/.github
        cp -r template/.github/defaults project/.github 
        
    - name: Open a PR for updates
      uses: peter-evans/create-pull-request@v3.5.0
      with:
        commit-message: Fetch template Github Action updates
        committer: AutoCommit <example@users.noreply.github.com>
        title: Update Github Actions
        body: This is an auto-generated PR with most recent updated in template Github Actions.
        labels: Github-action-updates, automated pr
        branch: template-action-updates
        path: project
        token: ${{ secrets.ORG_DISTRIBUTE_TOKEN }}


