# action.yml
name: 'Fetch Github repo names'
description: 'Fetch all repo name in the org account'
inputs:
  last_active:
    description: 'Number of day that last commit was made'
    required: true
    default: 28
  template:
    description: 'Name of the template repo'
    required: true
    default: 'SFLScientific/SFL-Template'
outputs:
  repos:
    description: 'A list of repo names'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.last_active }}
    - ${{ inputs.template }}