# action.yml
name: 'Fetch Github repo names'
description: 'Fetch all repo name in the org account'
inputs:
  token:
    description: 'Github token'
    required: true
    default: ""
  last_active:
    description: 'Number of day that last commit was made'
    required: false
    default: None
  org_name:
    description: 'Name of the organization'
    required: false
    default: ""
outputs:
  repos:
    description: 'A list of repo names'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.last_active }}
    - ${{ inputs.org_name }}
